version: '3.7'

services:
  app:
    container_name: pop-up-store-app
    build: .
    image: ghcr.io/redisgrafana/pop-up-store:latest
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redislabs/redismod
    ports:
      - "6379:6379"
      # - "${REDIS_PORT}:6379"
    # command: redis-server /data/redis.conf --requirepass ${REDIS_PASSWORD} --user ${REDIS_USERNAME}
    volumes:
      - redis_data:/data
      - ./redis.conf:/data/redis.conf:ro

  redis-insight:
    container_name: redis-insight
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"
    restart: always
    environment:
      - REDIS_0_HOST=redis
      - REDIS_0_PORT=6379
      # - REDIS_0_PORT=${REDIS_PORT}
      # - REDIS_0_PASSWORD=${REDIS_PASSWORD}
      - REDIS_0_TLS=false
      - REDIS_0_NAME=MyRedis
    depends_on:
      - redis

  grafana:
    container_name: grafana
    image: ghcr.io/redisgrafana/redis-app:latest
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_ENABLE_GZIP=true
      - GF_USERS_DEFAULT_THEME=dark
    volumes:
      - ./provisioning:/etc/grafana/provisioning
      - ./dashboards:/var/lib/grafana/dashboards
      - grafana_data:/var/lib/grafana      
    depends_on:
      - redis
    command: >
      sh -c "require('dotenv').config(); /run.sh"

volumes:
  grafana_data:
  redis_data:
